{{- if and .Values.jenkins.enabled .Values.externalSecrets.enabled .Values.externalSecrets.dockerRegistry.enabled }}
# ExternalSecret for Docker Hub credentials
# Fetches credentials from AWS SSM Parameter Store
# SSM Parameter: /weatherlabs/app/docker-registry-config
# Format: {"auths":{"https://index.docker.io/v1/":{"username":"liavvv","password":"dckr_pat_..."}}}
# 
# Used by:
# - BuildKit for pushing images to Docker Hub
# - Jenkins agents for pulling private images (if needed)
# 
# Registries:
# 1. liavvv/jenkins-agent - Jenkins agent base image
# 2. liavvv/quiz-app - Quiz application builds
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-registry-credentials
  namespace: {{ .Values.externalSecrets.namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.dockerRegistry.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Docker config.json format for authentication
        config.json: "{{ `{{ .dockerConfig | toString }}` }}"
  data:
  - secretKey: dockerConfig
    remoteRef:
      key: {{ .Values.externalSecrets.dockerRegistry.ssmParameterPath }}
{{- end }}
