{{- if and .Values.jenkins.enabled .Values.jenkins.serviceAccountToken.enabled }}
# Static token secret for Jenkins controller to authenticate with EKS
# Jenkins controller (running on EC2) uses this token to create pods for builds
# 
# Usage in Jenkins:
# 1. Get token: kubectl get secret jenkins-token -n jenkins -o jsonpath='{.data.token}' | base64 -d
# 2. Configure Jenkins Kubernetes plugin with:
#    - Kubernetes URL: https://kubernetes.default.svc
#    - Credentials: Secret text (paste token)
#    - Namespace: jenkins
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jenkins.serviceAccountToken.secretName }}
  namespace: {{ .Values.jenkins.namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: argocd
  annotations:
    kubernetes.io/service-account.name: {{ .Values.jenkins.serviceAccountName }}
    description: "Static token for Jenkins controller on EC2 to authenticate with EKS"
type: kubernetes.io/service-account-token
{{- end }}
