{{- if .Values.jenkins.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jenkins.serviceAccountName }}
  namespace: {{ .Values.jenkins.namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: argocd
  annotations:
    description: "Service account for Jenkins agents running on EKS"
{{- end }}
