---
# TargetGroupBinding for ArgoCD
# Connects ArgoCD service to ALB target group for HTTPS access
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argocd-tgb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # After infrastructure, before apps
spec:
  serviceRef:
    name: argocd-server
    port: 80
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-north-1:937137607178:targetgroup/devops-quiz-eks-argocd-tg/f97118006f3fdce5" # Injected by Terraform
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: "sg-0c08a24b548e2f8b9" # Injected by Terraform
        ports:
          - protocol: TCP
            port: 8080
