---
# TargetGroupBinding for ArgoCD
# Connects ArgoCD service to ALB target group for HTTPS access
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argocd-tgb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # After infrastructure, before apps
spec:
  serviceRef:
    name: argocd-server
    port: 80
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-north-1:610964304971:targetgroup/devops-quiz-eks-argocd-tg/f47e76626e7c8512" # Injected by Terraform
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: "sg-037b622b33d95a768" # Injected by Terraform
        ports:
          - protocol: TCP
            port: 8080
