---
# TargetGroupBinding for Loki
# Connects Loki service to ALB target group for HTTPS access
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: loki-tgb
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # After StorageClass and PVs
spec:
  serviceRef:
    name: loki
    port: 3100
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-north-1:937137607178:targetgroup/devops-quiz-eks-loki-tg/8dfc44cad3f077fa" # Injected by Terraform
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: "sg-0c08a24b548e2f8b9" # Injected by Terraform
        ports:
          - protocol: TCP
            port: 3100
