---
# PersistentVolume - Maps your existing EBS volume vol-0fc75d268cd28cb97
# Pre-created to bind with pre-created PVC for StatefulSet adoption
# NOTE: This PV is EXCLUSIVELY for MongoDB - labels and selector ensure only MongoDB PVC can claim it
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-ebs-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-30"  # Deploy early, before PVC
  labels:
    type: mongodb-data  # Must match selector in PVC
    component: mongodb  # Additional label for strict binding
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Empty string to avoid default SC injection
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0fc75d268cd28cb97
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - eu-north-1a
