---
# PersistentVolume - Maps your existing EBS volume vol-020cd08dcd3d4f91a
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-ebs-pv
  labels:
    type: mongodb-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Empty for manual binding
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-020cd08dcd3d4f91a
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - eu-north-1a  # Update with your AZ
