---
# ExternalSecret to pull MongoDB credentials from AWS SSM Parameter Store
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "-20"  # Create before MongoDB, same as PVC
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: mongodb
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: mongodb
          app.kubernetes.io/instance: mongodb
          app.kubernetes.io/component: mongodb
      data:
        mongodb-root-password: "{{ .rootPassword }}"
        mongodb-passwords: "{{ .rootPassword }}"  # Bitnami chart expects this key too
  data:
    - secretKey: rootPassword
      remoteRef:
        key: /quiz-app/mongodb/root-password
