apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: jenkins-platform
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/liav-hasson/quiz-app.git
    targetRevision: main
    path: gitops/jenkins-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Health checks
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: jenkins-token
    jsonPointers:
    - /data/token
    - /data/ca.crt
