---
# =============================================================================
# MongoDB - ArgoCD Application (Bitnami Chart)
# =============================================================================
# Single, simple MongoDB deployment using official Bitnami Helm chart
# Handles: StatefulSet, EBS volume, External Secrets, metrics - all in one!
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # Deploy after prerequisites, before apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mongodb
    server: https://kubernetes.default.svc
  project: default
  source:
    # Official Bitnami MongoDB chart
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.1.9  # Latest as of Nov 2024
    helm:
      values: |
        # Architecture
        architecture: standalone
        useStatefulSet: true
        
        # MongoDB image
        image:
          registry: docker.io
          repository: bitnami/mongodb
          tag: "latest"
        
        # Authentication - enabled with root user
        auth:
          enabled: true
          rootUser: root
          existingSecret: mongodb
        
        # Persistence - uses pre-created PVC (datadir-mongodb-0)
        # Pre-created PVC is bound to existing EBS volume via PV
        persistence:
          enabled: true
          existingClaim: "datadir-mongodb-0"  # Use pre-created PVC, don't create new one
          storageClass: ""  # Empty to prevent dynamic provisioning
          size: 20Gi
        
        # Resources
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        
        # Metrics
        metrics:
          enabled: true
        
        # Service
        service:
          type: ClusterIP
          ports:
            mongodb: 27017
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
