---
# =============================================================================
# MongoDB - ArgoCD Application (Bitnami Chart)
# =============================================================================
# Single, simple MongoDB deployment using official Bitnami Helm chart
# Handles: StatefulSet, EBS volume, External Secrets, metrics - all in one!
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # Deploy after prerequisites, before apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mongodb
    server: https://kubernetes.default.svc
  project: default
  source:
    # Custom MongoDB chart with full control over PVC binding
    repoURL: https://github.com/liav-hasson/quiz-app-gitops.git
    targetRevision: main
    path: mongodb
    helm:
      values: |
        # Use pre-created PVC (no volumeClaimTemplates!)
        persistence:
          usePrecreatedPVC: true
          pvcName: "datadir-mongodb-0"
          size: 20Gi
          storageClass: ""
          selector:
            matchLabels:
              type: mongodb-data
              component: mongodb
        
        # Authentication
        auth:
          enabled: true
          existingSecret: mongodb
        
        # Resources
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
