apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-multiplayer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/liavvv/quiz-app.git
    targetRevision: main
    path: gitops/quiz-multiplayer
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
