---
# =============================================================================
# Redis - ArgoCD Application
# =============================================================================
# Redis for multiplayer pub/sub and session state
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # Deploy after prerequisites, before apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/liav-hasson/quiz-app-gitops.git
    targetRevision: main
    path: redis
    helm:
      values: |
        app:
          name: redis
          replicaCount: 1
        
        persistence:
          enabled: true
          storageClass: "ebs-gp3"
          size: 1Gi
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
