apiVersion: v2
name: mongodb-init
description: MongoDB initialization job for quiz application data
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mongodb
  - initialization
  - data
  - quiz
maintainers:
  - name: DevOps Quiz Team
