{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ (index .Values.externalSecrets.secrets 0).name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ (index .Values.externalSecrets.secrets 0).target }}
    creationPolicy: Owner
  data:
    {{- range (index .Values.externalSecrets.secrets 0).keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
