{{- if .Values.externalSecrets.enabled -}}
---
# ClusterSecretStore: Defines how to access AWS SSM Parameter Store (cluster-scoped)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system

---
# ExternalSecret: Syncs OpenAI API key from SSM to Kubernetes Secret
{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .target }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .property }}
      remoteRef:
        key: {{ .key }}
{{- end }}
{{- end }}
